package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/dkempner/gqlgen-union-double-typename/graph/model"
)

// Union is the resolver for the union field.
func (r *queryResolver) Union(ctx context.Context) ([]model.Union, error) {
	return []model.Union{&model.A{ID: "1"}, &model.B{ID: "2"}}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
