// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Union interface {
	IsUnion()
}

type A struct {
	ID string `json:"id"`
}

func (A) IsUnion() {}

type B struct {
	ID string `json:"id"`
}

func (B) IsUnion() {}

type Query struct {
}
